kind: pipeline
name: default

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.12
    commands:
      - go test -v

  - name: build
    image: golang:1.12
    commands:
      - go mod download
      - git diff --quiet
      - go build -v

  - name: release
    image: golang:1.12
    commands:
      - "curl -sL https://git.io/goreleaser | bash"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event: tag
