kind: pipeline
name: default

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.12
    volumes:
      - name: cache
        path: /go/pkg
    commands:
      - go mod download
      # Fail if git state is dirty after download modules
      - git diff --quiet
      - make test

  - name: build
    image: golang:1.12
    volumes:
        - name: cache
          path: /go/pkg
    commands:
      - make build

  - name: release
    image: golang:1.12
    commands:
      - "curl -sL https://git.io/goreleaser | bash"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: cache
        path: /go/pkg
    when:
      event: tag
      branch:
      - master

volumes:
  - name: cache
    temp: {}